export type Section = { h?: string; p?: string[]; ul?: string[]; quote?: string };
export type Post = {
  slug: string; title: string; excerpt: string; image: string; date: string; read: string;
  category: string; lead: string; sections: Section[];
};

export const posts: Post[] = [
  {
    slug: "kitchen-remodel-cost-massachusetts",
    title: "How Much Does a Kitchen Remodel Cost in Massachusetts? (2026 Guide)",
    excerpt: "A clear breakdown of kitchen remodeling costs in MetroWest MA — by scope, materials, and what really drives the price.",
    image: "/images/kitchen.jpg",
    date: "June 20, 2026",
    read: "6 min read",
    category: "Cost Guide",
    lead: "“What will my kitchen remodel cost?” is the first question every homeowner asks — and the honest answer is: it depends. Here is a transparent, no-hype breakdown of what kitchen remodels actually cost in MetroWest Massachusetts, and what moves the number up or down.",
    sections: [
      { h: "Typical kitchen remodel cost ranges in MA", p: [
        "Costs vary with the size of your kitchen, the materials you choose, and how much you change the layout. As a general guide for Central Massachusetts homes:",
      ], ul: [
        "Minor refresh (paint, cabinet refacing, new counters & hardware): roughly $15,000–$25,000",
        "Mid-range remodel (new cabinets, countertops, backsplash, flooring, lighting): roughly $25,000–$45,000",
        "Major / high-end remodel (layout changes, island, custom cabinetry, premium finishes): roughly $45,000–$60,000+",
      ]},
      { h: "What drives the price", p: [
        "A few choices have an outsized effect on your final number. Knowing them up front helps you build a kitchen you love without surprises.",
      ], ul: [
        "Cabinets — usually the single biggest line item (stock vs. semi-custom vs. custom)",
        "Countertops — laminate, quartz, and natural stone span a wide price range",
        "Layout changes — moving plumbing, gas, or walls adds labor and trades",
        "Appliances — entry-level to professional-grade is a big swing",
        "Hidden conditions — older homes can hide outdated wiring or plumbing behind the walls",
      ]},
      { quote: "The smartest budget isn’t the lowest one — it’s the one with no surprises. That starts with a detailed, itemized estimate." },
      { h: "How to get the most value", p: [
        "You don't have to spend the most to get a kitchen you love. Keeping the existing layout, refacing solid cabinets, and choosing durable mid-range materials often delivers the biggest visual change per dollar. A good contractor will show you where to invest and where to save.",
      ]},
      { h: "Get a real number for your kitchen", p: [
        "Ranges are useful, but the only accurate figure is one based on your actual kitchen. Waterfront Construction provides free, detailed, itemized estimates for homeowners across Northborough and MetroWest — with honest options for every budget. Call (508) 816-2726 to get started.",
      ]},
    ],
  },
  {
    slug: "5-remodels-that-add-the-most-home-value",
    title: "5 Remodels That Add the Most Value to Your Home",
    excerpt: "Thinking about renovating? These projects give Massachusetts homeowners the best return on investment.",
    image: "/images/kitchen.jpg",
    date: "June 2, 2026",
    read: "5 min read",
    category: "Home Value",
    lead: "If you already own your home, the smartest renovations are the ones that make daily life better and pay you back at resale. Here are the five projects that consistently deliver the best return for MetroWest homeowners.",
    sections: [
      { h: "1. Kitchen refresh or full remodel", p: [
        "The kitchen sells the house — it's the first room buyers picture themselves in and the room your family lives in most. Even a mid-range update of cabinets, counters, and lighting returns a strong share of its cost while completely changing how the space feels every day.",
        "Not ready for a full gut? Refacing cabinets, swapping countertops, and improving the layout and lighting can transform a kitchen for a fraction of the price.",
      ]},
      { h: "2. Bathroom remodel", p: [
        "A clean, modern bathroom with quality tile and fixtures is one of the highest-impact upgrades you can make — especially in the older homes common across Central Massachusetts. Waterproofing done right also protects everything behind the walls.",
      ]},
      { h: "3. New siding", p: [
        "Curb appeal and protection in one. Fresh fiber-cement or vinyl siding instantly modernizes a home and shields it from New England weather — and it consistently ranks among the highest-ROI exterior projects nationwide.",
      ]},
      { h: "4. A deck or outdoor living space", p: [
        "Usable outdoor square footage is increasingly valuable, and a custom deck extends your living space for half the year. It's an upgrade you enjoy now and buyers reward later.",
      ]},
      { h: "5. A well-planned addition", p: [
        "When you love your location but need more room, an addition is almost always smarter than moving — no realtor fees, no moving trucks, and a home that finally fits your life.",
      ]},
      { quote: "The best remodel is the one that fits how you actually live — and pays you back when it's time to sell." },
      { h: "Which project is right for you?", p: [
        "Every home and budget is different. Request a free estimate and we'll walk you through the options that make the most sense for your goals.",
      ]},
    ],
  },
  {
    slug: "signs-its-time-to-replace-your-siding",
    title: "7 Signs It's Time to Replace Your Siding",
    excerpt: "Cracks, rot, rising energy bills? Here's how to know when siding repair becomes siding replacement.",
    image: "/images/siding.jpg",
    date: "May 18, 2026",
    read: "4 min read",
    category: "Exteriors",
    lead: "Siding protects everything behind it. When it starts to fail, moisture and cold follow — and small problems become expensive ones. Here's how to tell when it's time to replace rather than repair.",
    sections: [
      { h: "Watch for these warning signs", ul: [
        "Cracked, warped, or loose panels",
        "Peeling paint or wallpaper inside (a hidden-moisture clue)",
        "Rot, soft spots, or fungus on the boards",
        "Rising heating and cooling bills",
        "Needing to repaint every few years",
        "Faded, chalky color across large areas",
        "Visible gaps, holes, or pest entry points",
      ]},
      { h: "Repair or replace?", p: [
        "A few isolated issues can often be repaired. But when several of these signs show up together, replacement usually costs less over time than repeated patch jobs — and it dramatically improves comfort, energy efficiency, and curb appeal.",
      ]},
      { quote: "If you're patching siding every year, you're paying for a replacement on the installment plan." },
      { h: "Get an honest assessment", p: [
        "We're happy to take a look and tell you straight whether repair or replacement is the smarter move for your home. Estimates are always free.",
      ]},
    ],
  },
  {
    slug: "how-to-choose-a-contractor-in-massachusetts",
    title: "How to Choose a Remodeling Contractor in Massachusetts",
    excerpt: "Licensing, insurance, references — a simple checklist to hire with total confidence.",
    image: "/images/remodel.jpg",
    date: "April 29, 2026",
    read: "5 min read",
    category: "Hiring Guide",
    lead: "Hiring the right contractor is the difference between a smooth project and a stressful one. Use this checklist before you sign anything — it only takes a few minutes and can save you thousands.",
    sections: [
      { h: "Your pre-hire checklist", ul: [
        "Confirm Massachusetts Home Improvement Contractor licensing",
        "Verify they carry liability insurance (ask for proof)",
        "Ask who is actually on the job, day to day",
        "Get a written, itemized estimate — not a number on a napkin",
        "Check recent local references and photos of finished work",
        "Make sure permits and inspections are handled for you",
        "Trust the communication — clear before the job means clear during it",
      ]},
      { h: "Red flags to avoid", p: [
        "Be cautious of contractors who only take cash, won't put the scope in writing, pressure you to decide immediately, or can't show a license and insurance. The lowest bid is rarely the best value if it skips these basics.",
      ]},
      { quote: "Good contractors put everything in writing and answer the phone. If it's hard to reach them before the job, it'll be harder during it." },
      { h: "Why homeowners choose Waterfront", p: [
        "The owner is on every project, we're fully licensed and insured, and we put everything in writing — scope, timeline, and price. Reach out for a free, no-pressure estimate and see the difference.",
      ]},
    ],
  },
  {
    slug: "bathroom-remodel-cost-massachusetts",
    title: "How Much Does a Bathroom Remodel Cost in Massachusetts? (2026 Guide)",
    excerpt: "A transparent breakdown of bathroom remodeling costs in MetroWest MA — by scope, size, and the choices that move the price.",
    image: "/images/bathroom.jpg",
    date: "June 25, 2026",
    read: "5 min read",
    category: "Cost Guide",
    lead: "A bathroom remodel is one of the highest-impact upgrades you can make — but the price can swing widely depending on size and finishes. Here is an honest look at what bathroom remodels actually cost in MetroWest Massachusetts, and what moves the number.",
    sections: [
      { h: "Typical bathroom remodel cost ranges in MA", p: ["As a general guide for Central Massachusetts homes:"], ul: [
        "Powder room / cosmetic refresh (vanity, fixtures, paint, flooring): roughly $6,000–$12,000",
        "Mid-range full bathroom (new tile, tub/shower, vanity, fixtures, lighting): roughly $12,000–$25,000",
        "Primary / luxury bath (custom tile, walk-in shower, double vanity, layout changes): roughly $25,000–$45,000+",
      ]},
      { h: "What drives the price", ul: [
        "Tile and waterproofing — the biggest labor item in most bathrooms",
        "Tub-to-shower conversions and custom walk-in showers",
        "Moving plumbing or changing the layout adds trades and time",
        "Vanities, fixtures, and glass span a wide price range",
        "Hidden water damage in older homes can surface once walls open",
      ]},
      { quote: "In a bathroom, what you don't see matters most — proper waterproofing behind the tile is what protects your home for decades." },
      { h: "How to get the most value", p: ["Keeping the existing plumbing layout, choosing durable mid-range tile, and investing in quality waterproofing usually delivers the best long-term value. A good contractor will show you where it pays to splurge and where to save."]},
      { h: "Get a real number for your bathroom", p: ["The only accurate figure is one based on your actual bathroom. Waterfront Construction provides free, detailed, itemized estimates for homeowners across Northborough and MetroWest. Call (508) 816-2726 to get started."]},
    ],
  },
  {
    slug: "home-addition-cost-massachusetts",
    title: "How Much Does a Home Addition Cost in Massachusetts? (2026)",
    excerpt: "From bump-outs to second stories — what additions really cost in MetroWest MA, and when adding on beats moving.",
    image: "/images/addition.jpg",
    date: "June 12, 2026",
    read: "6 min read",
    category: "Cost Guide",
    lead: "When you love your neighborhood but need more room, a home addition is often smarter than moving. Here is a transparent look at what additions cost in Massachusetts and what drives the number.",
    sections: [
      { h: "Typical addition cost ranges in MA", p: ["Additions vary more than any other project, but as a general guide for Central Massachusetts:"], ul: [
        "Bump-out (a few extra feet to a kitchen or bath): roughly $20,000–$50,000",
        "Single-room addition (bedroom, family room, sunroom): roughly $50,000–$120,000",
        "Second-story addition or large multi-room build: roughly $120,000–$300,000+",
      ]},
      { h: "What drives the price", ul: [
        "Building out (foundation) versus building up (second story)",
        "Roofline changes and tying into the existing structure",
        "Plumbing, electrical, and HVAC for the new space",
        "Finish level — the same square footage can be basic or high-end",
        "Permits, engineering, and site conditions",
      ]},
      { quote: "An addition almost always costs less than the realtor fees, moving costs, and higher price tag of buying the bigger house down the street." },
      { h: "Is an addition right for you?", p: ["If your location and lot work, adding on keeps you in the home and neighborhood you love while building exactly the space your family needs. We'll help you weigh the options honestly."]},
      { h: "Get an estimate for your addition", p: ["Every addition is unique. Waterfront Construction provides free, detailed estimates for homeowners across Northborough and MetroWest. Call (508) 816-2726 to start the conversation."]},
    ],
  },
  {
    slug: "siding-replacement-cost-massachusetts",
    title: "Siding Replacement Cost in Massachusetts: 2026 Pricing Guide",
    excerpt: "Vinyl, fiber-cement, and engineered wood — what new siding costs in MetroWest MA and what affects the price.",
    image: "/images/home-exterior.jpg",
    date: "June 6, 2026",
    read: "5 min read",
    category: "Cost Guide",
    lead: "New siding is one of the highest-ROI exterior projects you can do — it protects your home and completely transforms its look. Here is what siding replacement actually costs in Massachusetts.",
    sections: [
      { h: "Typical siding cost ranges in MA", p: ["Pricing depends mostly on the material and the size and complexity of your home:"], ul: [
        "Vinyl siding: roughly $8,000–$20,000 for an average home",
        "Engineered wood: roughly $12,000–$28,000",
        "Fiber-cement (e.g. HardiePlank): roughly $15,000–$40,000+",
      ]},
      { h: "What drives the price", ul: [
        "Square footage and the number of stories",
        "Trim, soffit, fascia, and detail work",
        "Tear-off and disposal of the old siding",
        "Repairs to sheathing or moisture barriers once the old siding is off",
        "Material choice — vinyl is most affordable, fiber-cement most durable",
      ]},
      { quote: "Siding is your home's raincoat. Paying for proper house wrap and flashing underneath is what keeps New England weather out." },
      { h: "Which siding is right for New England?", p: ["Fiber-cement and quality vinyl both stand up well to our freeze-thaw winters. We'll walk you through the trade-offs in cost, maintenance, and look for your specific home."]},
      { h: "Get a siding estimate", p: ["Waterfront Construction provides free, itemized siding estimates across Northborough and MetroWest. Call (508) 816-2726 to get an accurate number for your home."]},
    ],
  },
  {
    slug: "signs-you-need-new-windows",
    title: "6 Signs It's Time to Replace Your Windows",
    excerpt: "Drafts, condensation, rising bills? How to know when window repair becomes window replacement in a New England home.",
    image: "/images/windows.jpg",
    date: "May 25, 2026",
    read: "4 min read",
    category: "Windows",
    lead: "Old windows quietly cost you money every winter. If you're noticing any of these signs, new energy-efficient windows can pay for themselves in comfort and lower bills.",
    sections: [
      { h: "Watch for these signs", ul: [
        "Drafts or cold spots near windows",
        "Condensation or fog between the panes",
        "Windows that stick, won't stay open, or won't lock",
        "Rising heating and cooling bills",
        "Visible rot, warping, or peeling on the frames",
        "Outside noise that comes through easily",
      ]},
      { h: "Why it matters in New England", p: ["Our long winters punish inefficient windows. Modern double- or triple-pane units with low-E coatings cut drafts, reduce noise, and lower energy bills — while making rooms far more comfortable year-round."]},
      { quote: "If you can feel a draft with the windows closed, you're paying to heat the outdoors." },
      { h: "Get an honest assessment", p: ["Sometimes a repair is all you need; sometimes replacement pays for itself quickly. We'll tell you straight. Call (508) 816-2726 for a free estimate."]},
    ],
  },
  {
    slug: "vinyl-vs-fiber-cement-siding",
    title: "Vinyl vs. Fiber-Cement Siding: Which Is Best for New England?",
    excerpt: "A side-by-side comparison of the two most popular siding choices for Massachusetts homes — cost, durability, and looks.",
    image: "/images/siding.jpg",
    date: "May 10, 2026",
    read: "5 min read",
    category: "Exteriors",
    lead: "Vinyl and fiber-cement are the two most popular siding choices for New England homes — and both are great options. The right one depends on your budget, your home, and how long you plan to stay. Here is an honest comparison.",
    sections: [
      { h: "Vinyl siding — the value choice", ul: [
        "Lowest upfront cost",
        "Never needs painting; easy to clean",
        "Many colors and profiles available",
        "Lighter-duty — can crack in extreme cold or hard impact",
      ]},
      { h: "Fiber-cement — the premium choice", ul: [
        "Extremely durable; resists rot, fire, and pests",
        "Holds paint for 10–15 years",
        "Looks like real wood and boosts resale value",
        "Higher upfront cost and heavier to install",
      ]},
      { quote: "There's no wrong answer here — it's about matching the material to your budget and how long you plan to own the home." },
      { h: "Our honest recommendation", p: ["If you want the lowest cost and least maintenance, quality vinyl is hard to beat. If you want the best durability and curb appeal — and plan to stay a while — fiber-cement is worth the investment. We install both and will tell you straight which fits your goals."]},
      { h: "Talk it through with a local pro", p: ["Request a free estimate and we'll compare both options for your exact home, with real numbers. Call (508) 816-2726."]},
    ],
  },
  {
    slug: "do-you-need-a-permit-to-remodel-massachusetts",
    title: "Do You Need a Permit to Remodel in Massachusetts?",
    excerpt: "When permits are required, what happens if you skip them, and how a licensed contractor handles it all for you.",
    image: "/images/remodel.jpg",
    date: "April 18, 2026",
    read: "4 min read",
    category: "Planning",
    lead: "Permits protect you — they make sure work is done to code and won't cause problems when you sell. Here is a plain-English guide to when you need one in Massachusetts and how the process works.",
    sections: [
      { h: "When you usually need a permit", ul: [
        "Structural changes (removing or moving walls, additions)",
        "Electrical, plumbing, or gas work",
        "New windows or doors in new openings",
        "Decks, and most kitchen and bathroom remodels",
        "Roofing and siding in many towns",
      ]},
      { h: "When you usually don't", p: ["Cosmetic work like painting, flooring, cabinet refacing, and minor repairs typically doesn't require a permit. Rules vary by town, so it's always worth confirming with your contractor."]},
      { quote: "Skipping permits can stall a home sale, void insurance claims, and cost far more to fix later than the permit ever would have." },
      { h: "The good news: we handle it", p: ["As a licensed Massachusetts Home Improvement Contractor, we pull the required permits and coordinate inspections for you — so the paperwork is never your problem."]},
      { h: "Have a project in mind?", p: ["We'll tell you up front exactly what your project needs. Call (508) 816-2726 for a free, no-pressure estimate."]},
    ],
  },
];
